maidsafe/safenetwork.tech

- src/constants.js
Resolved footer MaidSafe links to point proper location.
> Resolve footer MaidSafe links

- src/constants.js
@bochaco Let me know what you think of these link changes.
> chore/resource_links: points browser and web-hosting-manager links to latest release URI

- src/containers/privacy.js
> fix/privacy_links: fix broken links on Privacy page

- package-lock.json
- yarn.lock
Updated node deps to resolve vulnerability
> Resolve vulnerabilities deps

- src/containers/cookies.js
- src/containers/privacy.js
Updates to the cookie and privacy policy to account for the Crust Test(s) cookie usage.
> Update Cookie and Privacy Policy

- src/constants.js
- src/containers/partials/email_signup.js
fixes #127 and fixes #118 Updated to handle errors more efficiently.
> Update to handle errors

- .travis.yml
- package.json
- src/content/faqs.json
- test/broken_link_check.js
- test/server.js
- yarn.lock
Integrated CI for all three platforms to check broken links.
Known issue:
- `'https://www.cryptopia.co.nz/'` and `'https://t.me/safenetwork'` are temporarily excluded, as these links exist but respond with 404 and 501 respectively.
> CI Integration

- src/containers/press_kit.js
Updated Creative common licence text
> Fix: Updated CC licence text

- src/content/faqs.json
fixes #156 Paragraph is repeated twice in  https://safenetwork.tech/faq/#what-is-farming.
> FAQs Page-Repetition of content in #what is Farming?

- src/constants.js
- src/containers/safecoins.js
correct spelling of network and fix the link of the email app in timeline.
> fix/Safecoin: correct spelling of network in How do I buy SafeCoin?

- package.json
- yarn.lock
Resolved GH vulnerability issue by updating serve dev-depedency
> Resolve GH vulnerability issue

- src/utils.js
- src/v1.1/components/GlobalFooter/FooterSubscribe/FooterSubscribe.js
- src/v1.1/components/GlobalFooter/GlobalFooter.js
- src/v1.1/components/Subscribe/Subscribe.js
- src/v1.1/components/Subscribe/content.js
- src/v1.1/components/Subscribe/subscribe.sass
- src/v1.1/components/SubscribeForm/SubscribeForm.js
- src/v1.1/components/SubscribeForm/index.js
- src/v1.1/components/SubscribeForm/subscribeForm.sass
- src/v1.1/constant.js
- src/v1.1/styles/variables.sass
Fixes #184 - Refactor subscription code
> Subscription code clean-up

- src/v1.1/components/GlobalFooter/content.js
- src/v1.1/pages/Cookies/Cookies.js
- src/v1.1/pages/Cookies/Topic/Topic.js
- src/v1.1/pages/Cookies/Topic/index.js
- src/v1.1/pages/Cookies/Topic/topic.sass
- src/v1.1/pages/Cookies/content.js
- src/v1.1/pages/Cookies/cookies.sass
- src/v1.1/pages/Cookies/index.js
- src/v1.1/pages/Privacy/Privacy.js
- src/v1.1/pages/Privacy/content.js
- src/v1.1/pages/Privacy/index.js
- static.config.js
Fixes #247 - Cookie page implemented
And,
Privacy policy page implemented.
> Cookie and Privacy pages implemented

- src/v1.1/constant.js
- src/v1.1/pages/PressKit/MediaSnippet/MediaSnippet.js
- src/v1.1/pages/PressKit/Medias/Medias.js
- src/v1.1/pages/PressKit/Medias/medias.sass
- src/v1.1/pages/PressKit/PressKit.js
Fixes #279 - update presskit media hover and pressed state styling
> Press kit media hover and pressed state

- src/v1.1/pages/About/About.js
- src/v1.1/pages/About/about.sass
- src/v1.1/pages/About/content.js
- src/v1.1/pages/About/index.js
- src/v1.1/pages/NotFound/NotFound.js
- src/v1.1/pages/NotFound/content.js
- src/v1.1/pages/NotFound/index.js
- src/v1.1/pages/NotFound/notFound.sass
- static.config.js
Fixes #282 - About MaidSafe page implemented
And,
404 page implemented
> About MaidSafe and 404 pages implemented

- src/v1.1/components/GlobalFooter/globalFooter.sass
Fixes #278 - Footer newsletter hover and pressed state styling
> Footer newsletter title states

- src/v1.1/pages/Roadmap/AccordionItem/AccordionItem.js
- src/v1.1/pages/Roadmap/AccordionItem/accordionItem.sass
- src/v1.1/styles/colors.sass
Fixes #273 -  Roadmap accordion to handle close event to remove hash from url
Fixes #280 - Roadmap accordion styling for hover and pressed state
> Roadmap accordion fix

- src/v1.1/pages/SafeCoin/Banner/banner.sass
- src/v1.1/pages/SafeCoin/SafeCoin.js
- src/v1.1/pages/SafeCoin/content.js
- src/v1.1/pages/SafeCoin/safeCoin.sass
Fixes #322 - Full width view on XL screen
Fixes #343 - Poster as video poster
> Safecoin page minor styling issues

- src/v1.1/pages/Home/content.js
Fixes #370, #372, #373, #375, #376, #377 and #378
> Home page typo fixed

- src/pages/Cookies/Cookies.js
- src/pages/Cookies/content.js
resolves #365 - Cookie page content update for `No Cookie` policy
> No Cookie!

- src/pages/SafeCoin/content.js
> Typo issue on Safecoin page

- src/styles/shared/typography.sass
> Intro text font size in small breakpoints

- src/pages/HowItWorks/Banner/Banner.js
- src/pages/HowItWorks/Banner/banner.sass
> Full width video background for How it works page

- src/pages/Home/Banner/banner.sass
- src/pages/Roadmap/content.js
- yarn.lock
> Adding RFCs for Secure Message Delivery, and New data types + Other minor style fix

- src/pages/GetInvolved/Invite/invite.sass
Fixes #416 - Fix z-index issue
> Fixed overlay issue on invite modal

- src/components/QASection/QAItem/qaItem.sass
Fixes #412 - FAQ expand style issue
> Fixes FAQ line height issue on expand

- src/pages/Roadmap/content.js
> Updated Safecoin topics to RFC

- package.json
- yarn.lock
Updated `webpack-bundle-analyzer` dependency of `react-static` to resolve vulnerable issue
> Fixed vulnerable issue

- src/pages/GetInvolved/Invite/AccordionItem/AccordionItem.js
- src/pages/GetInvolved/Invite/AccordionItem/accordionItem.sass
- src/pages/GetInvolved/Invite/Invite.js
- src/utils.js
Fixes #413 - Remove download browser button for mobile breakpoints
> Download browser issue on mobile

- package.json
- src/components/BGVideo/BGVideo.js
- yarn.lock
Improved page load time with lazy load background video
> Lazy load background videos

- src/pages/Roadmap/content.js
> Roadmap Latest Update Text Changed

- src/App.js
Fixes #428 - Claim invite scroll fix
Fixes #418 - Main menu overlay fix
> Android scroll fix for fixed containers

- src/styles/shared/reset.sass
Fixes #427 - Font load issue fixed on page load
> Fix font load issue 

- package.json
- yarn.lock
Axios dependency updated to 0.18.0
> Vulnerable issue fixed - axios to v0.18.0

- src/index.js
- src/pages/Roadmap/content.js
Roadmap content updated with `Reliable Message Delivery` and `Secure Message Delivery`
> Roadmap message relay content update

- src/pages/Roadmap/content.js
> chore: update roadmap SMR and RMD

- src/pages/Roadmap/content.js
Fixes #451 and #454 
Updated Safe Cli and Data Manager status to Development on Roadmap page.
> Roadmap Update - Safe  CLI and Data Manager

- src/pages/SafeCoin/content.js
> Minor typo fix

- src/pages/Roadmap/content.js
> Updated Feature status for Reliable Message Delivery to COMPLETE

- src/constant.js
- src/pages/Roadmap/content.js
Fixes: #470 - SAFE Browser reference and Download link updated.
> SAFE Browser reference and download link updated

- src/pages/Roadmap/content.js
Fixes: #473 - Feature status of Secure Message Delivery has been updated to Development
> feature_status_updation

- src/pages/Roadmap/content.js
Fixes #476  : Updated latest update section in roadmap page - release of Safe Mobile Browser 0.1.0
> Roadmap Latest Update

- src/pages/Roadmap/content.js
Fixes: #478 #479 - Feature status of 'Unpublished Immutable Data' and 'Published and Unpublished Data Types' is updated to "Development"
> Feature status updated in Roadmap page

- src/pages/Roadmap/content.js
fixes #481.  status of 'Test Safecoin & Wallet' from 'RFC' to 'Development'.
> update 'Test Safecoin & Wallet ' status to 'Development'

- src/pages/Roadmap/content.js
Fixes #484 - Mobile Browser status is changed to Complete in Roadmap page
> Mobile Browser status updation

- src/pages/Roadmap/content.js
Fixes #485 and #483 - Feature status of Test Safecoin & Wallet changed to Complete and Farming to Development.
> Feature status updation

- src/pages/Privacy/content.js
FIxes #489 - Privacy policy section updated in Privacy policy page of safenetwork.tech website
> Privacy policy section updated.

- src/pages/Roadmap/content.js
Fixes: #494 - SAFE Browser status updated to Development
> SAFE Browser status update

- src/pages/Roadmap/content.js
Fixes: #493 - Latest update section updated
> Latest Update section update

- src/pages/Roadmap/content.js
Fixes: #495 & #496 - 'Published and Unpublished Data Types' and ''Unpublished ImmutableData Data Type' status updated to complete
> Published and Unpublished Data Types status updated

- src/pages/Roadmap/content.js
Fixes: #500 - XOR-URL status is updated to complete
> Feature status updated

- src/pages/FAQs/content.js
Fixes #507 - Browser release link updated to v.0.14.1
> Browser release link updated

- src/pages/Roadmap/content.js
> Roadmap update

- src/components/GlobalFooter/content.js
- src/components/GlobalHeader/content.js
- src/constant.js
- src/pages/FAQs/content.js
- src/pages/GetInvolved/Develop/develop.sass
- src/pages/GetInvolved/Engage/engage.sass
- src/pages/GetInvolved/content.js
- src/pages/Home/MainTextPanel/mainTextPanel.sass
- src/pages/Home/TextPanel/textPanel.sass
- src/pages/Home/content.js
- src/pages/HowItWorks/Topic/topic.sass
- src/pages/HowItWorks/content.js
- src/pages/PressKit/Downloads/DocDownload/docDownload.sass
- src/pages/PressKit/Downloads/DownloadContainer/downloadContainer.sass
- src/pages/PressKit/InterviewRequest/interviewRequest.sass
- src/pages/PressKit/Texts/texts.sass
- src/pages/Roadmap/Banner/banner.sass
- src/pages/Roadmap/content.js
- src/pages/SafeCoin/safeCoin.sass
> fix spacing issues and typos

- package.json
- src/pages/Home/content.js
- src/pages/Roadmap/Releases/Intro/Intro.js
- yarn.lock
Also updates some packages and removes an unnecessary div on the roadmap page.
> fix typo on homepage
